spring:
  profiles:
    active: dev
  datasource:
    maxPoolSize: 100
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://127.0.0.1:3307/restaurant_management?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    databaseName:
    serverName:
    username: root
    password:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        use-new-id-generator-mappings: true
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        org.hibernate.envers.audit_table_suffix: _history
        hibernate.jdbc.batch_size: 100
        hibernate.enable_lazy_load_no_trans: true
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.jdbc.batch_versioned_data: true

endpoints.health.sensitive: false