package com.aether.boiler.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
public enum Errors implements com.aether.boiler.enumInterfaces.Errors{

    RMS_INTERNAL_ERROR("INTERNAL_ERROR",1501, HttpStatus.INTERNAL_SERVER_ERROR,"Internal Error"),
    RMS_INVALID_STATE_TRANSITION("INVALID_STATE_TRANSITION",1502,HttpStatus.FORBIDDEN,"Invalid state transition."),
    RMS_SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE", 1503, HttpStatus.SERVICE_UNAVAILABLE, "Service is unavailable"),
    RMS_DOCUMENT_ALREADY_EXIST("RMS_DOCUMENT_ALREADY_EXIST", 1504, HttpStatus.BAD_REQUEST, "Document with same name already exist"),
    RMS_JSON_PARSING_ERROR("RMS_JSON_PARSING_ERROR", 1505, HttpStatus.INTERNAL_SERVER_ERROR, "Json Parsing error"),
    RMS_LOCATION_SERVICE_ERROR("RMS_LOCATION_SERVICE_ERROR", 1507, HttpStatus.INTERNAL_SERVER_ERROR, "Location Service error"),
    RMS_LOAD_SERVICE_ERROR("RMS_LOAD_SERVICE_ERROR", 1508, HttpStatus.INTERNAL_SERVER_ERROR, "Load Service error"),
    RMS_TRIP_SERVICE_ERROR("RMS_TRIP_SERVICE_ERROR", 1509, HttpStatus.INTERNAL_SERVER_ERROR, "Trip Service error"),
    RMS_ADDRESS_NOT_PASSED("RMS_ADDRESS_NOT_PASSED", 1510, HttpStatus.BAD_REQUEST, "Source/Destination address not passed"),
    RMS_ATTRIBUTE_NOT_PRESENT_FOR_TRIP_CREATION("RMS_ATTRIBUTE_NOT_PRESENT_FOR_TRIP_CREATION", 1511, HttpStatus.INTERNAL_SERVER_ERROR, "Trip creation attribute not present"),
    RMS_QUARTZ_ERROR_TRLI_CREATE("RMS_QUARTZ_ERROR_TRLI_CREATE", 1512, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_QUARTZ_ERROR_TRLI_CREATE"),
    RMS_QUARTZ_ERROR_TRLI_APPROVE("RMS_QUARTZ_ERROR_TRLI_APPROVE", 1513, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_QUARTZ_ERROR_TRLI_APPROVE"),
    RMS_QUARTZ_ERROR_TRLI_UPDATE("RMS_QUARTZ_ERROR_TRLI_UPDATE", 1514, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_QUARTZ_ERROR_TRLI_UPDATE"),
    RMS_CUSTOM_LOCK_CREATE_ERROR("RMS_CUSTOM_LOCK_CREATE_ERROR", 1515, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_CUSTOM_LOCK_CREATE_ERROR"),
    RMS_CUSTOM_LOCK_FIND_ERROR("RMS_CUSTOM_LOCK_FIND_ERROR", 1516, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_CUSTOM_LOCK_FIND_ERROR"),
    RMS_TRLI_SHOULD_BE_PRESENT("RMS_TRLI_SHOULD_BE_PRESENT", 1517, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_TRLI_SHOULD_BE_PRESENT"),
    RMS_SCHEDULING_ERROR("RMS_SCHEDULING_ERROR", 1518, HttpStatus.INTERNAL_SERVER_ERROR, "RMS_SCHEDULING_ERROR"),
    RMS_CONTAINER_SERVICE_ERROR("RMS_CONTAINER_SERVICE_ERROR", 1506, HttpStatus.INTERNAL_SERVER_ERROR, "Container Service error"),
    RMS_MEASURE_CONVERSION_ERROR("RMS_MEASURE_CONVERSION_ERROR", 1519, HttpStatus.BAD_REQUEST, "Error in converting metrics"),
    RMS_PAST_DATE_PASSED("RMS_PAST_DATE_PASSED", 1520, HttpStatus.BAD_REQUEST, "Bad Date Passed"),
    RMS_APPROVAL_SIMILARITY_EXCEPTION("RMS_APPROVAL_SIMILARITY_EXCEPTION", 1521, HttpStatus.BAD_REQUEST, "Approval requires trli to be similar"),
    ATLEAST_ONE_TRLI_SHOULD_BE_PASSED("ATLEAST_ONE_TRLI_SHOULD_BE_PASSED", 1522, HttpStatus.BAD_REQUEST, "Atleast one trli should be passed");

    @Getter
    private String code;
    @Getter
    private int internalErrorCode;
    @Getter
    private HttpStatus status;
    @Getter
    private String description;

}

